version = 1
SPDX-PackageName = "redkey-operator"
SPDX-PackageSupplier = "2025 Industria de Diseño Textil S.A."
SPDX-PackageDownloadLocation = "https://github.com/InditexTech/redkey-operator"

[[annotations]]
path = [
    ".github/CODEOWNERS",
    ".go-version",
    "repolinter.json",
    ".vscode/launch.json",
    "docs/files/redis-cluster-status-transitions.drawio",
    "docs/images/profiling-http-server.png",
    "docs/images/profiling-imports.png",
    "docs/images/redisbackup.png",
    "docs/images/redisk8slayout.png",
    "docs/images/redispvcnodeslayout.png",
    "docs/images/redkey-cluster-initialization.png",
    "docs/images/redkey-cluster-substatus-scalingdown-fast.png",
    "docs/images/redkey-cluster-substatus-scalingdown-slow.png",
    "docs/images/redkey-cluster-substatus-scalingup-fast.png",
    "docs/images/redkey-cluster-substatus-scalingup-slow.png",
    "docs/images/redkey-cluster-substatus-upgrading-fast.png",
    "docs/images/redkey-cluster-substatus-upgrading-slow.png",
    "go.sum",
    "test/cmd/data_44kl.txt",
    "config/crd/bases/redkey.inditex.dev_redkeyconfigs.yaml",
    "config/crd/bases/redkey.inditex.dev_redkeys.yaml",
    "config/manifests/bases/redkey-operator.clusterserviceversion.yaml",
    "config/rbac/role.yaml",
]
SPDX-FileCopyrightText = "2025 Industria Textil de Diseño, S.A."
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
    "docs/brand-kit/**",
    "docs/images/redkey-icon-*.png",
    "docs/images/redkey-horizontal-*.png",
]
SPDX-FileCopyrightText = "2025 Industria Textil de Diseño, S.A."
SPDX-License-Identifier = "Apache-2.0"