{
 "title": "Redkey Robin",
 "tags": [
  "redkey",
  "robin"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "job", "label": "Job", "query": "redkey-robin" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(process_start_time_seconds{job=~\"$job\"}, namespace)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(process_start_time_seconds{job=~\"$job\", namespace=~\"$namespace\"}, pod)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Robin Instances",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(process_start_time_seconds{job=~\"$job\", namespace=~\"$namespace\", pod=~\"$pod\"})"
    }
   ]
  },
  {
   "title": "Go Version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (version) (go_info{job=~\"$job\", namespace=~\"$namespace\", pod=~\"$pod\"})",
     "legendFormat": "{{version}}"
    }
   ]
  },
  { "title": "Kubernetes API Client", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Process Resident Memory (RSS)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=~\"$job\", namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "RSS"
    },
    {
     "expr": "process_virtual_memory_bytes{job=~\"$job\", namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "Virtual"
    }
   ]
  },
  {
   "title": "Go Heap Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "go_memstats_heap_inuse_bytes{job=~\"$job\", namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "Heap In-Use"
    },
    {
     "expr": "go_memstats_heap_idle_bytes{job=~\"$job\", namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "Heap Idle"
    },
    {
     "expr": "go_memstats_stack_inuse_bytes{job=~\"$job\", namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "Stack In-Use"
    }
   ]
  },
  {
   "title": "Memory Allocation Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(go_memstats_alloc_bytes_total{job=~\"$job\", namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval])",
     "legendFormat": "Alloc Rate"
    }
   ]
  },
  {
   "title": "GC Cycles Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(go_gc_duration_seconds_count{job=~\"$job\", namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval])",
     "legendFormat": "GC/s"
    }
   ]
  },
  { "title": "CPU & Scheduling", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Process CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=~\"$job\", namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval])",
     "legendFormat": "CPU cores"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "expr": "go_goroutines{job=~\"$job\", namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "Goroutines"
    }
   ]
  },
  {
   "title": "GC Pause Duration (quantiles)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "go_gc_duration_seconds{job=~\"$job\", namespace=~\"$namespace\", pod=~\"$pod\", quantile=\"0.5\"}",
     "legendFormat": "p50"
    },
    {
     "expr": "go_gc_duration_seconds{job=~\"$job\", namespace=~\"$namespace\", pod=~\"$pod\", quantile=\"0.75\"}",
     "legendFormat": "p75"
    },
    {
     "expr": "go_gc_duration_seconds{job=~\"$job\", namespace=~\"$namespace\", pod=~\"$pod\", quantile=\"1\"}",
     "legendFormat": "p100 (max)"
    }
   ]
  },
  {
   "title": "Threads & Memory Stats",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "targets": [
    {
     "expr": "go_memstats_mallocs_total{job=~\"$job\", namespace=~\"$namespace\", pod=~\"$pod\"} - go_memstats_frees_total{job=~\"$job\", namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "Live Objects"
    },
    {
     "expr": "go_memstats_heap_objects{job=~\"$job\", namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "Heap Objects"
    }
   ]
  },
  { "title": "File Descriptors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 } },
  {
   "title": "Open File Descriptors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "targets": [
    {
     "expr": "process_open_fds{job=~\"$job\", namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "Open FDs"
    },
    {
     "expr": "process_max_fds{job=~\"$job\", namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "Max FDs (limit)"
    }
   ]
  },
  {
   "title": "FD Utilisation",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_open_fds{job=~\"$job\", namespace=~\"$namespace\", pod=~\"$pod\"} / process_max_fds{job=~\"$job\", namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Goroutines per instance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "go_goroutines{job=~\"$job\", namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Open FDs per instance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "expr": "process_open_fds{job=~\"$job\", namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Requests by Method & Status (count)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(rest_client_requests_total{job=~\"$job\", namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval])) by (method, code)",
     "legendFormat": "{{method}} {{code}}"
    }
   ]
  },
  {
   "title": "Errors by Status (4xx + 5xx, count)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(rest_client_requests_total{job=~\"$job\", namespace=~\"$namespace\", pod=~\"$pod\", code=~\"4..\"}[$__rate_interval]))",
     "legendFormat": "4xx"
    },
    {
     "expr": "sum(increase(rest_client_requests_total{job=~\"$job\", namespace=~\"$namespace\", pod=~\"$pod\", code=~\"5..\"}[$__rate_interval]))",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "Kubernetes Container (cAdvisor + kube-state-metrics)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 }
  },
  {
   "title": "CPU Usage vs Requests/Limits (cores)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=~\"$namespace\", pod=~\"$pod\", container=\"robin\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{pod}} usage"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{namespace=~\"$namespace\", pod=~\"$pod\", container=\"robin\", resource=\"cpu\"}) by (pod)",
     "legendFormat": "{{pod}} limit"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{namespace=~\"$namespace\", pod=~\"$pod\", container=\"robin\", resource=\"cpu\"}) by (pod)",
     "legendFormat": "{{pod}} request"
    }
   ]
  },
  {
   "title": "CPU Throttling Ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_cfs_throttled_periods_total{namespace=~\"$namespace\", pod=~\"$pod\", container=\"robin\"}[$__rate_interval])) by (pod) / clamp_min(sum(rate(container_cpu_cfs_periods_total{namespace=~\"$namespace\", pod=~\"$pod\", container=\"robin\"}[$__rate_interval])) by (pod), 0.000001)",
     "legendFormat": "{{pod}} throttled"
    }
   ]
  },
  {
   "title": "Memory Working Set vs Requests/Limits",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=~\"$namespace\", pod=~\"$pod\", container=\"robin\"}) by (pod)",
     "legendFormat": "{{pod}} working set"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{namespace=~\"$namespace\", pod=~\"$pod\", container=\"robin\", resource=\"memory\"}) by (pod)",
     "legendFormat": "{{pod}} limit"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{namespace=~\"$namespace\", pod=~\"$pod\", container=\"robin\", resource=\"memory\"}) by (pod)",
     "legendFormat": "{{pod}} request"
    }
   ]
  },
  {
   "title": "Memory Usage % (working set / limit)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=~\"$namespace\", pod=~\"$pod\", container=\"robin\"}) by (pod) / clamp_min(sum(kube_pod_container_resource_limits{namespace=~\"$namespace\", pod=~\"$pod\", container=\"robin\", resource=\"memory\"}) by (pod), 1)",
     "legendFormat": "{{pod}} usage %"
    }
   ]
  },
  {
   "title": "Container Restarts (total)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{namespace=~\"$namespace\", pod=~\"$pod\", container=\"robin\"}) by (pod)",
     "legendFormat": "{{pod}} restarts"
    }
   ]
  },
  {
   "title": "Deployment Replicas (desired vs available)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas{namespace=~\"$namespace\", deployment=~\".*-robin\"}) by (deployment)",
     "legendFormat": "{{deployment}} desired"
    },
    {
     "expr": "sum(kube_deployment_status_replicas_available{namespace=~\"$namespace\", deployment=~\".*-robin\"}) by (deployment)",
     "legendFormat": "{{deployment}} available"
    }
   ]
  }
 ]
}