apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "redkey.inditex.dev/v1beta1",
          "kind": "Redkey",
          "metadata": {
            "name": "redis-cluster-example"
          },
          "spec": {
            "primaries": 3,
            "ephemeral": true,
            "accessModes": ["ReadWriteOnce"],
            "image": "redis:8.10",
            "purgeKeysOnRebalance": true,
            "resources": {
              "limits": {
                "cpu": "100m",
                "memory": "128Mi"
              }
            }
          }
        }
      ]
    capabilities: Auto Pilot
    categories: Database
    containerImage: redkey-operator:0.1.0
    description: Redkey Cluster Operator for Kubernetes. Manage your Redis/Valkey
      clusters seamlessly.
    repository: https://github.com/InditexTech/redkey-operator
  name: redkey-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: Redkey is the Schema for the redkeys API
      displayName: Redkey
      kind: Redkey
      name: redkeys.redkey.inditex.dev
      specDescriptors:
      - description: ReplicasPerPrimary specifies how many replicas should be attached
          to each Redis Primary node
        displayName: Number of replicas per Primary Node
        path: replicasPerPrimary
      version: ""
    - description: |-
        RedkeyConfig is the Schema for the redkeyconfigs API.
        It represents a sequenced desired-state snapshot created by the Operator and consumed by Robin.
      displayName: Redkey Config
      kind: RedkeyConfig
      name: redkeyconfigs.redkey.inditex.dev
      version: v1beta1
    - description: Redkey is the Schema for the redkeys API.
      displayName: Redkey
      kind: Redkey
      name: redkeys.redkey.inditex.dev
      version: v1beta1
  description: |
    Seamless Redkey Cluster Management on Kubernetes.

    The Redkey Operator simplifies the deployment and management of Redis/Valkey clusters on Kubernetes. It automates tasks such as scaling, failover, and configuration management, allowing you to focus on your applications while ensuring high availability and performance for your Redis instances.

    ### Documentation

    [Quick Start](https://github.com/InditexTech/redkey-operator/tree/main?tab=readme-ov-file#quick-start)

    Refer to the [operator guide](https://github.com/InditexTech/redkey-operator/blob/main/docs/operator-guide/toc.md) to have an overview of the main Redis configuration and management options, and a troubleshooting guide.

    If you are a developer, you'll find interesting information in the [developer guide](https://github.com/InditexTech/redkey-operator/blob/main/docs/developer-guide/toc.md).

    ### Contributing

    Contributions are welcome! Please read our [contributing guidelines](https://github.com/InditexTech/redkey-operator/blob/main/CONTRIBUTING.md) to get started.

    ### License

    This project is licensed under the Apache License 2.0 - see the [LICENSE](https://github.com/InditexTech/redkey-operator/blob/main/LICENSE) file for details.
  displayName: Redkey Operator
  icon:
  - base64data: PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAyMDAgMjAwIiByb2xlPSJpbWciIGFyaWEtbGFiZWw9IlJlZGtleSBjb2xvciBpY29uIj4KICA8dGl0bGU+UmVka2V5IGNvbG9yIGljb248L3RpdGxlPgogIDxnIHRyYW5zZm9ybT0idHJhbnNsYXRlKDAgMCkgc2NhbGUoMSkiPgo8cGF0aCBkPSJNMTAwIDggMTc4IDUzdjk0bC03OCA0NS03OC00NVY1M1oiIGZpbGw9Im5vbmUiIHN0cm9rZT0iIzMyNkNFNSIgc3Ryb2tlLXdpZHRoPSIxMCIgc3Ryb2tlLWxpbmVqb2luPSJyb3VuZCIvPgo8cGF0aCBkPSJNOTQgNzBoMTJ2NDBoMjB2MTFoLTIwdjNoMjB2MTFoLTIwdjE1YTYgNiAwIDAgMS0xMiAwWiIgZmlsbD0iI0U1MzkyRCIvPgo8cGF0aCBkPSJNMTAwIDMyYTIzIDIzIDAgMSAxIDAgNDYgMjMgMjMgMCAxIDEgMC00NlptMCAxNWE4IDggMCAxIDAgMCAxNiA4IDggMCAxIDAgMC0xNloiIGZpbGw9IiNFNTM5MkQiIGZpbGwtcnVsZT0iZXZlbm9kZCIvPgo8L2c+Cjwvc3ZnPgo=
    mediatype: image/svg+xml
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: true
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - redis
  - valkey
  - cluster
  - real-time-data
  - kubernetes
  - k8s
  - ocp
  links:
  - name: Redkey Operator Documentation
    url: https://github.com/InditexTech/redkey-operator/tree/main/docs
  - name: Redkey Operator Source Code
    url: https://github.com/InditexTech/redkey-operator
  - name: Redkey Robin Documentation
    url: https://github.com/InditexTech/redkey-robin/tree/main/docs
  - name: Redkey Robin Source Code
    url: https://github.com/InditexTech/redkey-robin
  maintainers:
  - email: lddpaas@inditex.com
    name: Inditex PaaS Team
  maturity: alpha
  minKubeVersion: 1.24.0
  provider:
    name: InditexTech
    url: https://github.com/InditexTech
  version: 0.0.0
